### ISSUE TITLE
App Crashes whenever a App is Opened

### ISSUE THREAD

**Issue by AruLNadhaN** [klinker24/Android-Blur-Launcher#2]
When a App is Opened or when I try to launch the settings of the launcher. It shows the below Exception.

So please help me to solve this issue ?

```
11-16 20:25:40.370 9568-9568/xyz.klinker.blur E/AndroidRuntime: FATAL EXCEPTION: main
                                                                Process: xyz.klinker.blur, PID: 9568
                                                                java.lang.RuntimeException: Unable to pause activity {xyz.klinker.blur/xyz.klinker.blur.launcher3.Launcher}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.widget.SwipeRefreshLayout.setProgressViewOffset(boolean, int, int)' on a null object reference
                                                                    at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3293)
                                                                    at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3252)
                                                                    at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3227)
                                                                    at android.app.ActivityThread.access$1100(ActivityThread.java:154)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1332)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:135)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5292)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
                                                                 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.widget.SwipeRefreshLayout.setProgressViewOffset(boolean, int, int)' on a null object reference
                                                                    at xyz.klinker.blur.extra_pages.weather_page.LauncherFragment.initLayout(LauncherFragment.java:42)
                                                                    at xyz.klinker.blur.extra_pages.BaseLauncherPage.onCreateView(BaseLauncherPage.java:64)
                                                                    at android.app.Fragment.performCreateView(Fragment.java:2053)
                                                                    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:894)
                                                                    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                                                                    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1049)
                                                                    at android.app.FragmentManagerImpl.dispatchPause(FragmentManager.java:1883)
                                                                    at android.app.Activity.performPause(Activity.java:6099)
                                                                    at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1310)
                                                                    at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3279)
                                                                    at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3252) 
                                                                    at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3227) 
                                                                    at android.app.ActivityThread.access$1100(ActivityThread.java:154) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1332) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                    at android.os.Looper.loop(Looper.java:135) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5292) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699) 
```

**Comment by klinker24** [comment]
The `blur_2` branch is stable and what is currently on the play store. The `master` branch is half way through a rewrite and I am not going to guarantee safety at this time.

Although this `NPE` would be very easy to solve if you just check out the logs. A view is null, specifically the `SwipeRefreshLayout` on the [weather_page.LauncherFragment](https://github.com/klinker24/Android-Blur-Launcher/blob/master/extra_pages/src/xyz/klinker/blur/extra_pages/weather_page/LauncherFragment.java)

If you check out the layout, you can see that it is in fact not in the [layout](https://github.com/klinker24/Android-Blur-Launcher/blob/master/extra_pages/res/layout/weather_page.xml).

I can just comment that part out I suppose, or you could do this.
