### ISSUE TITLE
icon pack not working

### ISSUE THREAD

**Issue by biloaramin** [klinker24/Android-Blur-Launcher#20]
when change icon pack it shows error and stops!

**Comment by klinker24** [comment]
Please post the stack trace for the exception. I am not seeing a problem at this time

**Comment by biloaramin** [comment]
thx for replay. i am new in android development. when i change icon pack
from default to other show error. unfortunately stop work.

**Comment by klinker24** [comment]
You can get a stack trace on Android studio. After it happens, copy the red text into this conversation.

**Comment by biloaramin** [comment]
ok

**Comment by biloaramin** [comment]
```
02-01 08:17:43.301 15734-15766/xyz.klinker.blur E/AndroidRuntime: FATAL EXCEPTION: launcher-loader
                                                                  Process: xyz.klinker.blur, PID: 15734
                                                                  java.lang.ArithmeticException: divide by zero
                                                                      at android.content.res.Resources.getDrawableForDensity(Resources.java:2088)
                                                                      at android.content.res.Resources.getDrawableForDensity(Resources.java:2047)
                                                                      at xyz.klinker.blur.launcher3.compat.LauncherActivityInfoCompatVL.getIcon(LauncherActivityInfoCompatVL.java:60)
                                                                      at xyz.klinker.blur.launcher3.IconCache.updateCacheAndGetContentValues(IconCache.java:418)
                                                                      at xyz.klinker.blur.launcher3.IconCache.addIconToDBAndMemCache(IconCache.java:388)
                                                                      at xyz.klinker.blur.launcher3.IconCache$SerializedIconUpdateTask.run(IconCache.java:822)
                                                                      at android.os.Handler.handleCallback(Handler.java:739)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:158)
                                                                      at android.os.HandlerThread.run(HandlerThread.java:61)
02-01 08:17:43.311 15734-15734/xyz.klinker.blur D/ViewRootImpl: #3 mView = null
02-01 08:17:43.321 15734-15734/xyz.klinker.blur E/ViewRootImpl: sendUserActionEvent() mView == null
```

**Comment by klinker24** [comment]
Thanks, will look into it when I get some time

**Comment by biloaramin** [comment]
ok thx klinker24.
