### ISSUE TITLE
Gives error in api 22

### ISSUE THREAD

**Issue by biloaramin** [klinker24/Android-Blur-Launcher#21]
```
02-01 16:10:10.981 27205-27205/xyz.klinker.blur E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: xyz.klinker.blur, PID: 27205
                                                                  java.lang.RuntimeException: Unable to start activity ComponentInfo{xyz.klinker.blur/xyz.klinker.blur.launcher3.Launcher}: android.view.InflateException: Binary XML file line #47: Error inflating class xyz.klinker.blur.launcher3.widget.WidgetsRecyclerView
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3125)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3224)
                                                                      at android.app.ActivityThread.access$1000(ActivityThread.java:198)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1682)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:145)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6843)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
                                                                   Caused by: android.view.InflateException: Binary XML file line #47: Error inflating class xyz.klinker.blur.launcher3.widget.WidgetsRecyclerView
                                                                      at android.view.LayoutInflater.createView(LayoutInflater.java:640)
                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750)
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
                                                                      at android.view.LayoutInflater.parseInclude(LayoutInflater.java:933)
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
                                                                      at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:450)
                                                                      at android.app.Activity.setContentView(Activity.java:2321)
                                                                      at xyz.klinker.blur.launcher3.Launcher.onCreate(Launcher.java:449)
                                                                      at android.app.Activity.performCreate(Activity.java:6500)
                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1120)
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3078)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3224) 
                                                                      at android.app.ActivityThread.access$1000(ActivityThread.java:198) 
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1682) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                      at android.os.Looper.loop(Looper.java:145) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6843) 
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199) 
                                                                   Caused by: java.lang.reflect.InvocationTargetException
                                                                      at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                      at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                                      at android.view.LayoutInflater.createView(LayoutInflater.java:614)
                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750) 
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:821) 
                                                                      at android.view.LayoutInflater.parseInclude(LayoutInflater.java:933) 
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:821) 
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:821) 
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:511) 
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:415) 
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:366) 
                                                                      at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:450) 
                                                                      at android.app.Activity.setContentView(Activity.java:2321) 
                                                                      at xyz.klinker.blur.launcher3.Launcher.onCreate(Launcher.java:449) 
                                                                      at android.app.Activity.performCreate(Activity.java:6500) 
                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1120) 
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3078) 
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3224) 
                                                                      at android.app.ActivityThread.access$1000(ActivityThread.java:198) 
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1682) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                      at android.os.Looper.loop(Looper.java:145) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6843) 
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199) 
                                                                   Caused by: java.lang.NoSuchMethodError: No virtual method getColor(I)I in class Landroid/content/Context; or its super classes (declaration of 'android.content.Context' appears in /system/framework/framework.jar:classes2.dex)
                                                                      at xyz.klinker.blur.launcher3.BaseRecyclerViewFastScrollBar.<init>(BaseRecyclerViewFastScrollBar.java:88)
                                                                      at xyz.klinker.blur.launcher3.BaseRecyclerView.<init>(BaseRecyclerView.java:62)
                                                                      at xyz.klinker.blur.launcher3.widget.WidgetsRecyclerView.<init>(WidgetsRecyclerView.java:0)
                                                                      at xyz.klinker.blur.launcher3.widget.WidgetsRecyclerView.<init>(WidgetsRecyclerView.java:0)
                                                                      at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                      at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
                                                                      at android.view.LayoutInflater.createView(LayoutInflater.java:614) 
                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750) 
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:821) 
                                                                      at android.view.LayoutInflater.parseInclude(LayoutInflater.java:933) 
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:821) 
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:821) 
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:511) 
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:415) 
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:366) 
                                                                      at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:450) 
                                                                      at android.app.Activity.setContentView(Activity.java:2321) 
                                                                      at xyz.klinker.blur.launcher3.Launcher.onCreate(Launcher.java:449) 
                                                                      at android.app.Activity.performCreate(Activity.java:6500) 
                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1120) 
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3078) 
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3224) 
                                                                      at android.app.ActivityThread.access$1000(ActivityThread.java:198) 
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1682) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                      at android.os.Looper.loop(Looper.java:145) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6843) 
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199) 
```

**Comment by biloaramin** [comment]
@klinker24 sir i made a change in BaseRecyclerViewFastScrollBar class and now it runs on api 22.

**Comment by klinker24** [comment]
@biloaramin can you make a PR for it?

**Comment by biloaramin** [comment]
@klinker24  yes sir i will make it.
