### ISSUE TITLE
Error please help

### ISSUE THREAD

**Issue by biloaramin** [klinker24/Android-Blur-Launcher#28]
```
java.lang.SecurityException: 
  at android.os.Parcel.readException(Parcel.java:1693)
  at android.os.Parcel.readException(Parcel.java:1646)
  at android.app.ActivityManagerProxy.isUserRunning(ActivityManagerNative.java:7000)
  at android.os.UserManager.isUserUnlocked(UserManager.java:1069)
  at android.os.UserManager.isUserUnlocked(UserManager.java:1063)
  at suma.launcher.launcher3.compat.UserManagerCompatVN.isUserUnlocked(UserManagerCompatVN.java:39)
  at suma.launcher.launcher3.LauncherModel$LoaderTask.loadWorkspace(LauncherModel.java:1761)
  at suma.launcher.launcher3.LauncherModel$LoaderTask.loadAndBindWorkspace(LauncherModel.java:1389)
  at suma.launcher.launcher3.LauncherModel$LoaderTask.run(LauncherModel.java:1488)
  at android.os.Handler.handleCallback(Handler.java:751)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:154)
  at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by klinker24** [comment]
Can you give me more information? How often does it happen, when does it happen, anything you can give here would be great. 

Looks to be an issue with loading a user on your phone.

**Comment by biloaramin** [comment]
i upload this project to google play and this error was reported by user. i think when a person deny storage permission in marshmallow or above and change user he will get this error.
